name: build-ipk (OpenWrt 24.10.2 x86_64)

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

env:
  RELEASE: 24.10.2
  TARGET: x86
  SUBTARGET: 64
  PKG_DIR_NAME: luci-app-adguardhome

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装构建工具
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential gawk unzip file libncurses5-dev \
            zlib1g-dev libssl-dev wget python3 git rsync time \
            zstd curl

      - name: 下载并解压 OpenWrt SDK
        run: |
          set -e
          BASE="https://downloads.openwrt.org/releases/${RELEASE}/targets/${TARGET}/${SUBTARGET}/"
          echo "BASE = $BASE"

          SDK_TARBALL="$(curl -fsSL "$BASE" | grep -o 'openwrt-sdk-[^"]*\.tar\.zst' | head -n1 || true)"
          if [ -z "$SDK_TARBALL" ]; then
            echo "ERROR: could not find SDK tarball under $BASE"
            exit 1
          fi
          SDK_URL="${BASE}${SDK_TARBALL}"
          echo "Resolved SDK_URL = $SDK_URL"

          mkdir -p "$GITHUB_WORKSPACE/_sdk"
          cd "$GITHUB_WORKSPACE/_sdk"
          wget -q "$SDK_URL" -O sdk.tar.zst
          tar --zstd -xf sdk.tar.zst
          SDK_DIR="$(find . -maxdepth 1 -type d -name 'openwrt-sdk-*' | head -n1)"
          echo "SDK_DIR=$GITHUB_WORKSPACE/_sdk/$SDK_DIR" >> $GITHUB_ENV

      - name: 注入 PKG_RELEASE
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "Using tag: $TAG"
          if grep -qE '^PKG_RELEASE:=' Makefile; then
            sed -i "s/^PKG_RELEASE:=.*/PKG_RELEASE:=${TAG}/" Makefile
          else
            echo "PKG_RELEASE:=${TAG}" >> Makefile
          fi
          echo "== Makefile (snippet) =="
          grep -E '^(PKG_NAME|PKG_VERSION|PKG_RELEASE)[:]?=' Makefile || true

      - name: 准备 SDK 内的包树
        run: |
          set -eux
          cd "$SDK_DIR"
          cat > feeds.conf.default << 'EOF'
          src-git packages https://git.openwrt.org/feed/packages.git;openwrt-24.10
          src-git luci https://git.openwrt.org/project/luci.git;openwrt-24.10
          src-git routing https://git.openwrt.org/feed/routing.git;openwrt-24.10
          src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-24.10
          EOF

          ./scripts/feeds update -a
          ./scripts/feeds install -a

          mkdir -p package/${PKG_DIR_NAME}
          rsync -a --delete "$GITHUB_WORKSPACE/" "package/${PKG_DIR_NAME}/" \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '_sdk'

      - name: 生成默认配置
        run: |
          cd "$SDK_DIR"
          make defconfig

      - name: 编译包
        run: |
          cd "$SDK_DIR"
          make package/${PKG_DIR_NAME}/compile -j$(nproc) V=s

      - name: 收集 IPK
        run: |
          cd "$SDK_DIR"
          mkdir -p "$GITHUB_WORKSPACE/out"
          find bin/packages -type f -name "*${PKG_DIR_NAME}*ipk" -print -exec cp -f {} "$GITHUB_WORKSPACE/out/" \;
          find bin/packages -maxdepth 3 -type f -name 'Packages*' -exec cp -f {} "$GITHUB_WORKSPACE/out/" \;

          cd "$GITHUB_WORKSPACE/out"
          sha256sum *.ipk > SHA256SUMS.txt || true
          ls -l

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ipks-${{ github.ref_name }}-x86_64
          path: out/
          if-no-files-found: error